In [1]:
# Importación de librerías.
import numpy as np
import pandas as pd

## Iris.csv

In [2]:
# Cargar el dataset.
df = pd.read_csv("C:/Users/Cristian/Programacion/Python/Redes_Neuronales/Iris.csv")
# df = pd.read_csv("C:/Programacion/Python/Redes_Neuronales/Iris.csv")

In [3]:
df = df.drop(['Id'], axis=1)

#### Discretización

In [4]:
# Discretización de los datos[Clases]. (0, 1)
# Cambiar las etiquetas de las especies a números.
df["Species"].unique()
df["Species"].value_counts()
df["Species"] = df["Species"].map(
    {"Iris-setosa": 0,
     "Iris-versicolor": 1,
     "Iris-virginica": 2})
df["Species"].unique()
df["Species"].value_counts()

# Eliminar la especie Iris-virginica
# df = df.drop(df[df["Species"] == 2].index)

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [5]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

##### Datos de entrenamiento y prueba

In [6]:
from sklearn.model_selection import train_test_split

X = df.copy()
X.drop(['Species'], axis=1, inplace=True)
y = df.copy()
y = y['Species'] 

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

### FUNCIONES DE ACTIVACIÓN

In [8]:
# FUNCIONES DE ACTIVACIÓN

# - 1. Sigmoide (un solor valor)
def sigmoide(x):
    return 1/(1 + np.exp(-x))

# - 1.1. Derivada de la función sigmoide
def sigmoide_derivada(x):
    return x * (1 - x)

# - 2. ReLU
def  relu(x):
    return np.maximum(0, x)

# - 2.1. Derivada de la función ReLU
def relu_derivada(x):
    return np.where(x>=0, 1, 0)

# - 3. Tangente Hiperbólica (tanh)
def tanh(x):
    return np.tanh(x)
# - 3.1. Derivada de la función Tangente Hiperbólica
def tanh_derivada(x):
    return 1 - np.tahn(x)**2

# - Escalon
def escalon(x):
    return np.where(x>=0, 1, 0)

# - 4. Softmax
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

# - 4.1 Derivada de la función Softmax
def softmax_derivada(x):
    s = x.reshape(-1, 1) # Asegurar que es un vector columna
    return np.diagflat(s) - np.dot(s, s.T) # np.dot(s, s.T) es la multiplicación de matrices

# - Mish
def mish(x):
    return x * np.tanh(np.log(1 + np.exp(x)))

In [9]:
# Función para calcular la sumatoria.
#! Cambiar a .dot()
def sumaMuchos (*args):
    suma = 0
    for arg in args:
        suma += arg
    return suma

In [10]:
# Funcion de Error.
def error(y, y_pred):
    return y - y_pred

### 1.- Definir la topologia de la red neuronal

####       1.1. Cantidad de capas de la Red Neuronal

In [11]:
# numCapas = int(input("Ingrese la cantidad de capas ocultas de la red neuronal: ")) + 2
numCapas = 3
print(f"La red neuronal tiene {numCapas} capas.")

La red neuronal tiene 3 capas.


####       1.2. Cantidad de Neuronas en cada capa

In [12]:
numNeuronas = [4, 3, 3]
# numNeuronas = []
# for i in range(numCapas):
#     neuronas = int(input(f"Ingrese la cantidad de neuronas en la capa {i+1}:"))
#     numNeuronas.append(neuronas)
print(f"Cantidad de neuronas por capa: {numNeuronas}")

Cantidad de neuronas por capa: [4, 3, 3]


In [13]:
# Bias por capa
np.random.seed(0)

biasCapas = []
for i in range(numCapas):
    bias = np.random.rand(numNeuronas[i])
    biasCapas.append(bias)
print(f"Bias por capa:")
for i in biasCapas:
    print(i)

Bias por capa:
[0.5488135  0.71518937 0.60276338 0.54488318]
[0.4236548  0.64589411 0.43758721]
[0.891773   0.96366276 0.38344152]


####       1.3 Función de Activación en capas ocultas

In [14]:
# fnActivacionCapas = []
fnActivacionCapas =['1', '1']
# for i in range(numCapas-1):
#     print(f"FUNCIONES DE ACTIVACIÓN: \n1.- Sigmoide\n 2.- ReLU \n 3.- Tangente Hiperbólica. \n4.- Softmax")
#     fn = input(f"Ingrese la función de activación de la capa {i+2}: ")
#     fnActivacionCapas.append(fn)
print(f"Función de activación en cada capa: {fnActivacionCapas}")

Función de activación en cada capa: ['1', '1']


### 2.- Implementar FeedForward

#### 2.1 Crear la matriz de pesos

In [15]:
# pesos = np.array([])
np.random.seed(0)
pesos = []
numCaracteristicas = df.shape[1]-1
for i in range(numCapas-1):
    w = np.random.rand(numNeuronas[i], numNeuronas[i+1])
    pesos.append(w)

# pesos = np.array(pesos)
print("Matriz de pesos:")
for i in pesos:
    print(i)

Matriz de pesos:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]
[[0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]]


In [22]:
pesos2 = []
for i in range(numCapas-1):
    w2 = np.random.uniform(-1, 1, (numNeuronas[i], numNeuronas[i+1]))
    pesos2.append(w)

In [16]:
print(pesos[0])

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]


In [17]:
# Capa 1 -> Capa 2
c2 = np.dot(x_train.values[0], pesos[0])
for i in range(len(c2)):
    # c2[i] += biasCapas[0][i]
    c2[i] = sigmoide(c2[i])
# Capa 2 -> Capa 3
c3 = np.dot(c2, pesos[1])
for i in range(len(c3)):
    # c3[i] += biasCapas[0][i]
    c3[i] = sigmoide(c3[i])

In [18]:
print(c2)

[0.99330979 0.99717142 0.99790765]


In [19]:
print(c3)

[0.80653578 0.85909059 0.86731177]


#### 2.2 Aplicar FeedForward y obtener una salida

##### FeedForward

In [20]:
def FeedForward(Entrada, numCapas, pesos):
    a = [(Entrada)]
        
    for i in range(numCapas -1):
        if (i < numCapas - 1):
            z = np.dot(pesos[i], a[-1])
            
            if fnActivacionCapas[i] == "1":
                a.append(sigmoide(z))
            elif fnActivacionCapas[i] == "2":
                a.append(relu(z))
            elif fnActivacionCapas[i] == "3":
                a.append(tanh(z))
            elif fnActivacionCapas[i] == "4":
                a.append(softmax(z))
    return a

In [21]:
pesosT = []
for i in pesos:
    pesosT.append(i.T)

In [38]:
x = FeedForward(x_train.values[0], numCapas, pesosT)
x

[array([4.6, 3.6, 1. , 0.2]),
 array([0.99330979, 0.99717142, 0.99790765]),
 array([0.80653578, 0.85909059, 0.86731177])]

In [54]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: Species, dtype: int64

In [40]:
# Error cuadrático medio
def ECM(y, y_pred):
    return np.mean((y - y_pred)**2)

In [41]:
valoresx = x_train.values[:50, :]
# errorTotal = 0
for i in range(len(valoresx)):
    x = FeedForward(x_train.values[i], numCapas, pesosT)
    indiceAlto = np.argmax(x[-1])
    print(f"Salida: {x[-1]}")
    print(f"Obtenido: {indiceAlto}")
    print(f"Esperado: {y_train.values[i]}")
    print(f"Error: {ECM(y_train.values[i], x[-1])}")    
    print()


Salida: [0.80653578 0.85909059 0.86731177]
Obtenido: 2
Esperado: 0
Error: 0.7135887678490099

Salida: [0.80721326 0.85982872 0.86776952]
Obtenido: 2
Esperado: 0
Error: 0.7146408711520998

Salida: [0.80738239 0.86001857 0.86786567]
Obtenido: 2
Esperado: 1
Error: 0.024718609131006986

Salida: [0.80679959 0.8593617  0.8675475 ]
Obtenido: 2
Esperado: 0
Error: 0.714022256581211

Salida: [0.80638248 0.85890812 0.86726546]
Obtenido: 2
Esperado: 0
Error: 0.7133750846363851

Salida: [0.80737944 0.86001463 0.86786616]
Obtenido: 2
Esperado: 2
Error: 1.334545830816265

Salida: [0.80738145 0.86001736 0.86786563]
Obtenido: 2
Esperado: 1
Error: 0.024718845308722242

Salida: [0.80692458 0.85950395 0.86761305]
Obtenido: 2
Esperado: 0
Error: 0.7142089066073115

Salida: [0.80686437 0.85943928 0.86756722]
Obtenido: 2
Esperado: 0
Error: 0.714112959909508

Salida: [0.80705091 0.85964744 0.867671  ]
Obtenido: 2
Esperado: 0
Error: 0.7143926228159002

Salida: [0.8073743  0.86000822 0.86786539]
Obtenido: 2
Espe

In [39]:
# print(FeedForward(x_train.values[0], numCapas, pesosT))

##### FeedBackward 1

In [44]:
# Computo del error de la ultima capa
# (sigmoide, sigmoide)
errorUltimaCapa = error(y_train.values[0], x[-1]) * sigmoide_derivada(x[-1])

In [45]:
# Retropropagación del error a la capa anterior
errorCapaAnterior = np.dot(pesosT[-1], errorUltimaCapa) * sigmoide_derivada(x[-2])

In [49]:
# Calculamos las derivadas de la capa usando el error
# dW = []
# dW.append(np.dot(x[-2].reshape(-1, 1), errorUltimaCapa.reshape(-1, 1)).T)
# dW.append(np.dot(x[-3].reshape(-1, 1), errorCapaAnterior.reshape(-1, 1)).T)

In [50]:
errorCapaAnterior

array([-4.63556426e-04, -5.16974003e-05, -5.24544360e-05])

##### FeedBackward 2 (No finalizado)

In [77]:
tazaAprendizaje = 0.5
epocas = 1000

In [78]:
from sklearn.model_selection import train_test_split

X = df.copy()
# X = X.drop('Species', axis=1)
y = df.copy()
y = y['Species'] 

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [79]:
# Vector (A) x matriz (B) multiplicación
def vec_mat_bias(A, B, bias):
    C = []
    for i in range(len(B[0])):
        C.append(0)
    
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[j] += A[k] * B[k][j]
        C[j] += bias[j]
    
    return C


# Matriz (A) x vector (B) multipilicacion (para propagación hacia atrás)
def mat_vec(A, B): 
    C = []
    for i in range(len(A)):
        C.append(0)
    
    for i in range(len(A)):
        for j in range(len(B)):
            C[i] += A[i][j] * B[j]
    
    return C

In [80]:
import random

# Inicializar los pesos y sesgos con valores de 0
weights = []
for i in range(len(numNeuronas) - 1):
    weights.append([])
    for j in range(numNeuronas[i]):
        weights[i].append([])
        for k in range(numNeuronas[i + 1]):
            weights[i][j].append(0)

weight = []
for i in range(len(weights[0])):
    weight.append([])
    for j in range(len(weights[0][i])):
        weight[i].append(weights[0][i][j])

weight_2 = []
for i in range(len(weights[1])):
    weight_2.append([])
    for j in range(len(weights[1][i])):
        weight_2[i].append(weights[1][i][j])

bias_list = []
for i in range(1, len(numNeuronas)):
    bias_list.append([])
    for j in range(numNeuronas[i]):
        bias_list[i-1].append(0)

bias = []
for i in range(len(bias_list[0])):
    bias.append(bias_list[0][i])

bias_2 = []
for i in range(len(bias_list[1])):
    bias_2.append(bias_list[1][i])


# Inicializar los pesos con valores aleatorios entre -1 y 1
for i in range(numNeuronas[0]):
    for j in range(numNeuronas[1]):
        weight[i][j] = 2 * random.random() - 1

for i in range(numNeuronas[1]):
    for j in range(numNeuronas[2]):
        weight_2[i][j] = 2 * random.random() - 1

In [ ]:
for e in range(epocas):
    cost_total = 0
    for idx, data_list in enumerate(x_train): # Actualizar para cada dato; SGD


        # Forward propagacion
        h_1 = vec_mat_bias(data_list, weight, bias)
        h_1 = np.dot(data_list, weight) + bias
        X_1 = sigmoide2(h_1)
        h_2 = vec_mat_bias(X_1, weight_2, bias_2)
        X_2 = sigmoide2(h_2)

        # Convertir objetivo a One-hot
        target = [0] * numNeuronas[-1]
        target[int(y_train[idx])] = 1


        # Funcion de coste: Error cuadratico medio
        eror = 0
        for i in range(numNeuronas[-1]):
            eror +=  0.5 * (target[i] - X_2[i]) ** 2 
        cost_total += eror

# PRUEBAS (IGNORAR)

In [2]:
# Pesos de prueba (W)
# (3, 4)
pruebaW = np.array([[0.17, 0.32, 0.12, 2.53], 
                    [0.33, 0.55, -0.37, 0.21],
                    [1.04, -0.27, -0.19, 1.57]])


# pruebaX1 = np.array([[0.12, 0.57, 0.25, 0.34]])
# pruebaX2 = np.array([[0.45, 0.32, 0.14, 0.61]])
# pruebaX3 = np.array([[0.88, 0.91, 0.03, 0.15]])

# Datos de prueba (mini-batch) o (X)}
# (4, 3)
pruebaX = np.array([[0.12, 0.45, 0.88], 
                    [0.57, 0.32, 0.91],
                    [0.25, 0.14, 0.03],
                    [0.34, 0.61, 0.15]])

# bias de prueba (b)
pruebab = [2.23, 2.75, 2.57]

# Operacion broadcast
# NN(X,W,b)
# pruebaZ = np.dot(pruebaW, pruebaX1.T) 
# pruebaZ = np.dot(pruebaW, pruebaX2.T) 
# pruebaZ = np.dot(pruebaW, pruebaX3.T) 
pruebaZ = np.dot(pruebaW, pruebaX) 

In [3]:
pruebaZ

array([[1.093 , 1.739 , 0.8239],
       [0.332 , 0.4008, 0.8113],
       [0.4572, 1.3127, 0.8993]])

In [4]:
for i in range(len(pruebaZ)):
    pruebaZ[i] += pruebab[i]

In [5]:
pruebaZ # score
# pruebaProductoPunto.max()

array([[3.323 , 3.969 , 3.0539],
       [3.082 , 3.1508, 3.5613],
       [3.0272, 3.8827, 3.4693]])

##### Softmax

In [6]:
# Exponecial de los scores
pruebaExp = np.exp(pruebaZ)
pruebaExp

array([[27.74345621, 52.93157279, 21.19785506],
       [21.80196275, 23.3547409 , 35.20893903],
       [20.6393614 , 48.55513712, 32.1142546 ]])

In [7]:
print(np.sum(pruebaExp, axis=0))

[ 70.18478035 124.84145081  88.52104868]


In [8]:
# Suma
pruebaSoftmax = pruebaExp / np.sum(pruebaExp, axis=0)
pruebaSoftmax

array([[0.39529163, 0.42399037, 0.23946683],
       [0.31063662, 0.18707521, 0.39774652],
       [0.29407175, 0.38893442, 0.36278665]])

In [9]:
# Loss function
loss = -np.log(pruebaSoftmax)

In [10]:
# print(-np.log(pruebaSoftmax[0][0]))
print(loss)

[[0.92813148 0.85804454 1.42934036]
 [1.16913148 1.67624454 0.92194036]
 [1.22393148 0.94434454 1.01394036]]


In [11]:
# El total de la suma de las probabilidades debe ser 1
print(np.sum(pruebaSoftmax, axis=0))

[1. 1. 1.]


In [12]:
# One-hot encoding
gato =  [1, 0, 0]
perro = [0, 1, 0]
ave =   [0, 0, 1]

In [13]:
gatoP = -np.log(pruebaSoftmax[0][0])
perroP = -np.log(pruebaSoftmax[1][1])
aveP = -np.log(pruebaSoftmax[2][2])
# Cost function
J = (gatoP + perroP + aveP) / 3
J

1.2061054613393196