#### Se usará el conjunto de datos FashionMNIST para entrenar un modelo de red neuronal que reconozca imágenes como camiseta/top, pantalón, jersey, vestido, abrigo, sandalia, camisa, deportivas, bolso o botas bajas.

## Que son los tensores?
Los tensores son una estructura de datos esoecializada, es muy similar a los arrays y matrices.

En Pytorch usamos tensores para codificar las entradas y salidas de un modelo, así como los parametros del modelo

In [2]:
%matplotlib inline
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_data value: \n {x_data} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_data after * 2 operation: \n {x_data} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_data value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array afeter * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_data afeter * 2 operation: 
 tensor([[1, 2],
        [3, 4]]) 

